### PR TITLE
Feature/setup api

### PR DESCRIPTION
**Pull request by call203**
Screenshot 2023-10-02 at 21 23 11
This is Prisma Shema to run 
-  Prisma Module and Service
- Generate Controller, Module, Service with Prisma setting

### CODE REVIEW

**Comment by 1Solon** [comment]
Does Swagger have a natural integration with Prisma? If so yes, please. OpenAPI is the best API.

**Comment by 1Solon** [comment]
Also, annoying. 
image

I'll do a PR after this to add both to git ignore, my bad for it not being there originally. Let me fix the conflicts for now.

**Comment by 1Solon** [comment]
Nice. Thanks

**Review by 1Solon — APPROVED** [review]
I'll leave it to @KaustubhTrivedi to confirm (unsure what I am looking at) but from what I can read- looks good to me.

**Comment by call203** [comment]
@KaustubhTrivedi ,
I couldn't check if this code ran well because of Prisma schema's absent, as i mentioned.
After you've done your job, just let me know and let's integrate your code with mine.
I'll be waiting for you :)

**Review by 1Solon — APPROVED** [review]

**Pull request merged**
