### PR TITLE
feature/jwt-and-auth

### PR DESCRIPTION
**Pull request by 1Solon**
# Adds full Auth and Various Fixes

So, this is a lot. In short, our backend is fully authenticated!

In broad strokes, everything is now split into "guards", see below:

## LocalRequestGuard

This one prevents users from accessing endpoints that are not on localhost. This is useful for endpoints that are only meant to be accessed by the backend, such as the `/getMany` endpoints.

```ts
@Injectable()
export class LocalRequestGuard implements CanActivate {
  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest();
    if (!this.isLocalRequest(request)) {
      throw new ForbiddenException(
        'This endpoint is accessible only from localhost.',
      );
    }
    return true;
  }

  private isLocalRequest(request: any): boolean {
    const ip = request.ip;
    return ip === '127.0.0.1' || ip === '::1';
  }
```

## User-Ownership Guard

This one prevents users from accessing data that is not theirs. This is useful for endpoints that are meant to be accessed by the user, such as the `/getOne` endpoints.

```ts
@Injectable()
export class UserOwnershipGuard implements CanActivate {
  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest();
    const userIdFromParam = Number(request.params.id);
    const userIdFromToken = request.user.user_id;

    if (userIdFromParam !== userIdFromToken) {
      throw new ForbiddenException(
        "You are not authorized to access this user's data",
      );
    }

    return true;
  }
}
```

## jwt-auth

This enables JWT authentication. It's pretty simple, and is mostly just a wrapper around the `passport-jwt` package.

```ts
@Injectable()
export class JwtAuthGuard extends AuthGuard('jwt') {}
```

If you want to the exacts, take a look at [users jwt-strat](/src/users/jwt-strategy.ts).

## IMPORTANT

The JWT now makes it hard to do anything with Swagger, so I've added a button to the top right of the Swagger UI that allows you to authenticate. You can use the following credentials:

```json
{
    "email": "john.doe@email.com",
    "password": "securePass123"
}
```
Picture for context:
image

**Make sure to authenticate or you can't use the API!**

### Changelog

- Adds passport and config
- Seed now hashes passwords
- Enabled .env management
- Removes superflous provider table
- Updates packages
- Updates seed to support table changes
- Removes provider table
- Replace "provider" with seperate user
- Modifes spec to respect usertype
- Adds userType to DTO
- Adds auth button to swagger
- Implements jwt-auth
- Defines "local-only" decorator
- Implements Local-Only and JWT
- Removes unecessary decorator
- Implements guards
- Moves guard to "guards"
- Moves guard to "guards"
- Implements local request guard
- Implements user ownership guard
- Updates specs to accomodate changes
- Minor contactsService changes
- Fixes findChat
- Minor profiles changes
- Minor whitespace changes
- Changes status 201 to a 200
- Adds service validation

### CODE REVIEW

**Comment by call203** [comment]
Screenshot 2023-10-26 at 10 21 08
why provider is searched in User table?

**Comment by 1Solon** [comment]
image

If you see here, I'm destructuring the contact that is being passed in. Searching by provider_id. It seems to work when tested.

**Comment by 1Solon** [comment]
> image
> If you see here, I'm destructuring the contact that is being passed in. Searching by provider_id. It seems to work when tested.

**Comment by call203** [comment]
Oh, I didn't notice that you removed Provider table. 
But now I'm struggling with handle your API in your brunch.
I need your help today :(

**Comment by 1Solon** [comment]
> Oh, I didn't notice that you removed Provider table. But now I'm struggling with handle your API in your brunch. I need your help today :(

Sorry for changing things so drastically! We'll chat at the lab

**Review by KaustubhTrivedi — APPROVED** [review]

**Comment by KaustubhTrivedi** [comment]
Where can I get API for authorization?

**Pull request merged**
